version: "3"

services:
  mysql: 
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./settings/.env.mysql.db
    ports:
      - 3306:3306
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./settings/.env.mongo.db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    env_file:
      - ./settings/.env.express
    volumes:
      - mongodb-data:/data/db
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    command: >
      ash -c "python wait_for_mysql.py 
      && uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./backend/:/backend/
    expose:
      - 8080
    depends_on:
      - mongodb

volumes:
  mongodb-data: null
  mysql-data: null