version: "3"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./settings/.env.db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    env_file:
      - ./settings/.env.express
    volumes:
      - mongodb-data:/data/db
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    command: >
      ash -c "uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./backend/:/backend/
    expose:
      - 8080
    depends_on:
      - mongodb

volumes:
  mongodb-data: null